spring:
  application:
    name: SPRING-CLOUD-SOLR
  zipkin:
    # zipkin 监控地址
    base-url: http://spring-cloud-zipkin:8084
  boot:
    admin:
      client:
        # spring-clouda-dmin 监控地址
        url: http://spring-clouda-admin:8087

  # mysql druid 配置
  datasource:
    druid:
      url: jdbc:mysql://119.3.252.69:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.fjhckj.springcloudsso.user.entity
  mapper-locations: classpath:mapper/*.xml


#端口
server:
  port: 8101

eureka:
  instance:
    # 注入自身ip到eureka
    prefer-ip-address: true
    # 自定义eureka的服务地址显示方式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-eureka:8081/eureka/
#监控检查
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info